// Generated by scripts/generate_levels.py (or generate-levels.mjs) — do not hand-edit.
export const LEVELS = [
  {
    "id": "tutorial-1",
    "chapter": "tutorial",
    "title": "First Steps",
    "file": "./tutorial-1.svg"
  },
  {
    "id": "oneway-1",
    "chapter": "oneway",
    "title": "No Turning Back",
    "file": "./oneway-1.svg"
  },
  {
    "id": "oneway-2",
    "chapter": "oneway",
    "title": "Don't Trust Your Eyes",
    "file": "./oneway-2.svg"
  },
  {
    "id": "closing-1",
    "chapter": "closing",
    "title": "The Sealed Door",
    "file": "./closing-1.svg"
  },
  {
    "id": "closing-2",
    "chapter": "closing",
    "title": "Before You Go",
    "file": "./closing-2.svg"
  },
  {
    "id": "limited-1",
    "chapter": "limited",
    "title": "Two Crossings",
    "file": "./limited-1.svg"
  },
  {
    "id": "limited-2",
    "chapter": "limited",
    "title": "Spend Wisely",
    "file": "./limited-2.svg"
  },
  {
    "id": "linked-1",
    "chapter": "linked",
    "title": "Choose a Branch",
    "file": "./linked-1.svg"
  },
  {
    "id": "linked-2",
    "chapter": "linked",
    "title": "What You Give Up",
    "file": "./linked-2.svg"
  },
  {
    "id": "toggle-1",
    "chapter": "toggle",
    "title": "Flip the Route",
    "file": "./toggle-1.svg"
  },
  {
    "id": "toggle-2",
    "chapter": "toggle",
    "title": "Two Switches",
    "file": "./toggle-2.svg"
  },
  {
    "id": "combo-1",
    "chapter": "combo",
    "title": "Commit and Follow Through",
    "file": "./combo-1.svg"
  },
  {
    "id": "combo-2",
    "chapter": "combo",
    "title": "Budget the Route",
    "file": "./combo-2.svg"
  },
  {
    "id": "combo-3",
    "chapter": "combo",
    "title": "The Living Labyrinth",
    "file": "./combo-3.svg"
  },
  {
    "id": "capstone-1",
    "chapter": "capstone",
    "title": "The Vault",
    "file": "./capstone-1.svg"
  },
  {
    "id": "capstone-2",
    "chapter": "capstone",
    "title": "Any Order",
    "file": "./capstone-2.svg"
  },
  {
    "id": "capstone-3",
    "chapter": "capstone",
    "title": "No Second Chances",
    "file": "./capstone-3.svg"
  }
];
